on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    - develop
  #   paths:
  #   - .github/workflows/semgrep.yml
 # schedule:
 # - cron: '0 0 * * 0'
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep
        run: |
          cp /home/runner/work/_temp/_github_workflow/event.json ./.github_event_path.json
          if [ "${{github.event.pull_request.number}}" != "" ]; then
            echo "Setting up diff scan env vars..."
            export SEMGREP_BASELINE_REF=$GITHUB_BASE_REF
            export SEMGREP_PR_ID=${{github.event.pull_request.number}}
          fi
          printenv | sort | egrep "^GITHUB_" | tee .env
          printenv | sort | egrep "^RUNNER_" | tee -a .env
          printenv | sort | egrep "^SEMGREP_" | tee -a .env
          docker run --rm -v "${PWD}:/src" \
          --env-file .env \
          -e SEMGREP_APP_TOKEN=${{ secrets.SEMGREP_APP_TOKEN }} \
          -e GITHUB_EVENT_PATH="/src/.github_event_path.json" \
          returntocorp/semgrep:latest-nonroot \
          /bin/bash -c "whoami; pwd; ls -la; printenv | sort; semgrep ci"
        
