on:
  workflow_dispatch: {}
  # pull_request: {}
  # push:
  #   branches:
  #   - main
  #   - master
  #   - develop
  #   paths:
  #   - .github/workflows/semgrep.yml
 # schedule:
 # - cron: '0 0 * * 0'
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep
        run: |
          printenv | egrep "^GITHUB_" | tee .env
          docker run --rm -v "${PWD}:/src" \
          returntocorp/semgrep:pr-8685-nonroot \
          /bin/bash -c "whoami; pwd; ls -la; printenv | sort"
        
