on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    - develop
    paths-ignore:
      - '.github/workflows/semgrep.yml'
      - '.github/workflows/semgrep2.yml'
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep
        run: |
          cp $GITHUB_EVENT_PATH ./.github_event_path.json
          printenv | sort | egrep "^GITHUB_" | tee .env
          printenv | sort | egrep "^RUNNER_" | tee -a .env
          printenv | sort | egrep "^SEMGREP_" | tee -a .env
          sudo chown -R 1000:1000 .
          docker run --rm -v "${PWD}:/src" \
          --env-file .env \
          -e SEMGREP_APP_TOKEN=${{ secrets.SEMGREP_APP_TOKEN }} \
          -e GITHUB_EVENT_PATH="/src/.github_event_path.json" \
          returntocorp/semgrep:latest-nonroot \
          /bin/bash -c "whoami; pwd; ls -la; ls -la .git/; semgrep ci"
          
