on:
  workflow_dispatch: {}
  # pull_request: {}
  # push:
  #   branches:
  #   - main
  #   - master
  #   - develop
  #   paths:
  #   - .github/workflows/semgrep.yml
 # schedule:
 # - cron: '0 0 * * 0'
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep
        run: |
          printenv | sort | egrep "^GITHUB_" | tee .env
          cat /home/runner/work/_temp/_github_workflow/event.json
          docker run --rm -v "${PWD}:/src" \
          --env-file .env \
          -e SEMGREP_APP_TOKEN=${{ secrets.SEMGREP_APP_TOKEN }} \
          returntocorp/semgrep:latest-nonroot \
          /bin/bash -c "whoami; pwd; ls -la; printenv | sort"
        
