on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    - develop
    paths-ignore:
      - '.github/workflows/semgrep.yml'
      - '.github/workflows/semgrep2.yml'
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep
        run: |
          cp /home/runner/work/_temp/_github_workflow/event.json ./.github_event_path.json
          cat .github_event_path.json
          # if [ "${{github.event.pull_request.number}}" != "" ]; then
          #   echo "Setting up diff scan env vars..."
          #   export SEMGREP_BASELINE_REF=$GITHUB_BASE_REF
          #   export SEMGREP_PR_ID=${{github.event.pull_request.number}}
          # fi
          printenv | sort | egrep "^GITHUB_" | tee .env
          printenv | sort | egrep "^RUNNER_" | tee -a .env
          printenv | sort | egrep "^SEMGREP_" | tee -a .env
          docker run --rm -v "${PWD}:/src" \
          --env-file .env \
          -e SEMGREP_APP_TOKEN=${{ secrets.SEMGREP_APP_TOKEN }} \
          -e GITHUB_EVENT_PATH="/src/.github_event_path.json" \
          sinat101/semgrep-debug:latest \
          /bin/bash -c "whoami; pwd; ls -la; printenv | sort; ls -la .git/"
                    
          # semgrep ci --debug --no-suppress-errors

          # -e SEMGREP_REPO_NAME=$GITHUB_REPOSITORY \
          # -e SEMGREP_REPO_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY \
          # -e SEMGREP_PR_ID=${{github.event.pull_request.number}} \
          # -e SEMGREP_COMMIT=${{github.event.pull_request.head.sha}} \
          # -e SEMGREP_BRANCH=$GITHUB_HEAD_REF \
          # -e SEMGREP_BASELINE_REF=origin/$GITHUB_BASE_REF \
