on:
  workflow_dispatch: {}
  # pull_request: {}
  # push:
  #   branches:
  #   - main
  #   - master
  #   - develop
  #   paths:
  #   - .github/workflows/semgrep.yml
 # schedule:
 # - cron: '0 0 * * 0'
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    # container:
    #   image: returntocorp/semgrep:latest-nonroot
    steps:
      - uses: actions/checkout@v4
      - uses: docker://returntocorp/semgrep:latest-nonroot
        env:
          HOME: "/src"
        with:
          args: /bin/bash -c "whoami; pwd; ls -la; printenv | sort"
